version = 0.1

[default]
[default.global.parameters]
stack_name = "serverless-backend-api"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
confirm_changeset = false
resolve_s3 = true
s3_bucket = ""
s3_prefix = "serverless-backend-api"
stack_name = "serverless-backend-api"

[default.local_start_api.parameters]
port = 3000
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
container_env_var_file = ""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
skip_pull_image = false

